# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40bab3425b3e229200c90f70c253deb4fa423d59cd39f736886018f86bc29a39e984f0825e9e6dfcf7f02db3284daa905f4ea4b93de31bd45221c96ecfc0f9c6

test:
  secret_key_base: 257080e88c42266eee93988f938c24cbeb53b12b66183c61492c7aee35d4c2e1ba3c9d04e7a1a0f28244337de62ceb93994cd108293e959c7fe87ceb603a2d4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
